---
- name: Update apt cache and install base packages
  become: true
  apt:
    update_cache: yes
    name: "{{ system_packages }}"
    state: present

- name: Auto-install NVIDIA driver
  become: true
  command: ubuntu-drivers autoinstall
  register: ubuntu_drivers_autoinstall
  changed_when: "'No drivers found' not in ubuntu_drivers_autoinstall.stdout"
