all:
  vars:
    dataset_root: "/dataset"
    num_datasets: 8
    mamba_python_version: "3.12"
    mamba_env_name: "venv"
    mamba_root_prefix: "{{ ansible_user_dir }}/mamba"
    mamba_bin: "{{ ansible_user_dir }}/bin/micromamba"
    project_repo_url: "https://github.com/younes-nb/predictive-k8s-autoscaling"
    project_root: "{{ ansible_user_dir }}/predictive-k8s-autoscaling"

  hosts:
    mlwisc:
      old_gpu: true
