all:
  vars:
    install_nvidia: true
    skip_apt_update: false
    mamba_python_version: "3.12"
    mamba_env_name: "venv"
    mamba_root_prefix: "{{ ansible_user_dir }}/mamba"
    mamba_bin: "{{ ansible_user_dir }}/bin/micromamba"
    project_repo_url: "https://github.com/younes-nb/predictive-k8s-autoscaling"
    project_root: "{{ ansible_user_dir }}/predictive-k8s-autoscaling"
    git_user_name: "younes-nb"
    git_user_email: "younesnikbin@gmail.com"

  hosts:
    ml:
